{% set python_min = "3.10" %}
{% set name = "txl-text-editor" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_text_editor-{{ version }}.tar.gz
  sha256: 525befee602389ce6c665aa4ba33f1f6dbcee28bddbd4ca0150f502e0ccfc56f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - txl_text_editor

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/text_editor
  summary: TXL plugin for a text editor
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/text_editor
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
