{% set python_min = "3.10" %}
{% set name = "txl-text-editor" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_text_editor-{{ version }}.tar.gz
  sha256: 6c7011f7a40e582d686ab53e02da3eb0ba1a353fb2e8b6973c10ddc029b2b58b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_text_editor

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/text_editor
  summary: TXL plugin for a text editor
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/text_editor
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
