{% set name = "txl-text-editor" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_text_editor-{{ version }}.tar.gz
  sha256: 9a4516a0803e35d9eb74eefc5efd43a94a03e51f9804058da9c6b4558994ceed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl >=0.2.18,<0.3.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_text_editor

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/text_editor
  summary: TXL plugin for a text editor
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/text_editor
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
